export async function api(path:string,body?:unknown){const r=await fetch(path,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:undefined);const j=await r.json();if(!r.ok)throw Error(j.error||"Request failed");return j}
const enc=new TextEncoder();
export const digest=async(v:string,a:string)=>[...new Uint8Array(await crypto.subtle.digest(a,enc.encode(v)))].map(x=>x.toString(16).padStart(2,"0")).join("");
export const fileDigest=async(f:File,a:string)=>[...new Uint8Array(await crypto.subtle.digest(a,await f.arrayBuffer()))].map(x=>x.toString(16).padStart(2,"0")).join("");
export const identifyHash=(v:string)=>{const n=v.trim().length;return !/^[a-f0-9]+$/i.test(v)?"Not hexadecimal":({32:"MD5 (likely)",40:"SHA-1 (likely)",56:"SHA-224 (likely)",64:"SHA-256 (likely)",96:"SHA-384 (likely)",128:"SHA-512 (likely)"}as Record<number,string>)[n]||"Unknown hash length"};
export const urlEncode=(v:string)=>encodeURIComponent(v);export const urlDecode=(v:string)=>decodeURIComponent(v);export const b64e=(v:string)=>{const bytes=enc.encode(v);let s="";for(const x of bytes)s+=String.fromCharCode(x);return btoa(s)};export const b64d=(v:string)=>{const s=atob(v.trim());return new TextDecoder().decode(Uint8Array.from(s,c=>c.charCodeAt(0)))};export const hexe=(v:string)=>[...enc.encode(v)].map(x=>x.toString(16).padStart(2,"0")).join("");export const hexd=(v:string)=>{const x=v.replace(/\s/g,"");if(!/^(?:[0-9a-f]{2})+$/i.test(x))throw Error("Invalid hex");return new TextDecoder().decode(new Uint8Array((x.match(/../g)||[]).map(y=>parseInt(y,16))))};
export const urlInfo=(v:string)=>{const u=new URL(v);return {protocol:u.protocol,hostname:u.hostname,port:u.port||((u.protocol==="https:")?"443":u.protocol==="http:"?"80":"default"),origin:u.origin,path:u.pathname,query:u.search||"(none)",hash:u.hash||"(none)"}};
export const passwordScore=(v:string)=>{let s=0;if(v.length>=12)s+=25;if(/[a-z]/.test(v))s+=15;if(/[A-Z]/.test(v))s+=15;if(/\d/.test(v))s+=15;if(/[^A-Za-z0-9]/.test(v))s+=20;if(/(.)\1{2,}/.test(v))s-=15;if(/password|qwerty|123456|admin/i.test(v))s-=35;return {score:Math.max(0,Math.min(100,s)),entropy:Math.round(v.length*Math.log2(new Set(v).size||1))}};
export const regexInfo=(p:string,f:string)=>{try{new RegExp(p,f)}catch(e){return {valid:false,warnings:[e instanceof Error?e.message:"Invalid regex"]}}const w:string[]=[];if(/\([^)]*[+*][^)]*\)[+*]/.test(p))w.push("Nested quantifiers may cause catastrophic backtracking.");if(/\.[+*]/.test(p))w.push("Wildcard repetition can be expensive.");if(!w.length)w.push("No obvious catastrophic-backtracking pattern detected.");return {valid:true,warnings:w}};
export const csp=(o:Record<string,boolean>)=>{const p=["default-src 'self'"];if(o.scripts)p.push("script-src 'self'");if(o.styles)p.push("style-src 'self'");if(o.images)p.push("img-src 'self' data: https:");if(o.fonts)p.push("font-src 'self' https:");if(o.frames)p.push("frame-ancestors 'none'");if(o.connect)p.push("connect-src 'self' https:");return p.concat(["object-src 'none'","base-uri 'self'","form-action 'self'"]).join("; ")+";"};
export const cidr=(v:string)=>{const [ip,p]=v.split("/"),n=Number(p),o=ip.split(".").map(Number);if(o.length!==4||n<0||n>32)throw Error("Use IPv4 CIDR such as 192.168.1.0/24");const x=o.reduce((a,b)=>(a*256+b)>>>0,0),m=n?0xffffffff<<(32-n):0,net=(x&m)>>>0,bc=(net|(~m>>>0))>>>0,f=(z:number)=>[z>>>24,(z>>>16)&255,(z>>>8)&255,z&255].join(".");return {network:f(net),broadcast:f(bc),mask:f(m>>>0),hosts:n>=31?2**(32-n):2**(32-n)-2,first:f(n>=31?net:net+1),last:f(n>=31?bc:bc-1)}};
export const meta=async(f:File)=>{const u=new Uint8Array(await f.arrayBuffer()),r:any={name:f.name,type:f.type,size:f.size};if(f.type==="image/jpeg"&&u[0]===255&&u[1]===216){r.format="JPEG";for(let i=2;i+8<u.length;){if(u[i]!==255){i++;continue}const m=u[i+1],l=(u[i+2]<<8)|u[i+3];if(m>=192&&m<=195){r.height=(u[i+5]<<8)|u[i+6];r.width=(u[i+7]<<8)|u[i+8]}if(m>=224&&m<=239){if(!r.exifSegments)r.exifSegments=[];r.exifSegments.push("APP"+(m-224)+" ("+l+" bytes)");}if(m===218||m===217)break;i+=2+l}}return r};
export const logAnalyze=(t:string)=>{const l=t.split(/\r?\n/),ips=new Map<string,number>();let failed=0,errors=0,sql=0,xss=0;for(const s of l){for(const m of s.matchAll(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g))ips.set(m[0],(ips.get(m[0])||0)+1);if(/failed|invalid password|login failed/i.test(s))failed++;if(/\berror\b|exception| 5\d\d /i.test(s))errors++;if(/union.+select|sleep\(|or\s+1=1/i.test(s))sql++;if(/<script|javascript:|onerror=/i.test(s))xss++}return {lines:l.length,failed,errors,possibleSQLi:sql,possibleXSS:xss,topIPs:[...ips.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10)};}
export const yaraLite=(r:string,t:string)=>{const sec=(r.match(/strings:\s*([\s\S]*?)condition:/i)||[])[1]||"",ss=[...sec.matchAll(/\$\w+\s*=\s*["']([^"']+)["']/g)].map(x=>x[1]),m=ss.filter(x=>t.includes(x));return {rule:(r.match(/rule\s+(\w+)/i)||[])[1]||"unnamed",strings:ss,matched:m,count:m.length,note:"Lightweight browser tester; not a full YARA engine."}};
export const pcap=async(f:File)=>{const u=new Uint8Array(await f.arrayBuffer());if(u.length<24)throw Error("PCAP too small");const magic=[...u.slice(0,4)].map(x=>x.toString(16).padStart(2,"0")).join(""),le=magic==="d4c3b2a1"||magic==="4d3cb2a1";if(!le&&magic!=="a1b2c3d4"&&magic!=="a1b23c4d")throw Error("Unsupported PCAP");const d=new DataView(u.buffer),link=d.getUint32(20,le);let off=24,packets=0,tcp=0,udp=0,icmp=0,bytes=0;while(off+16<=u.length){const n=d.getUint32(off+8,le);if(off+16+n>u.length)break;packets++;bytes+=n;const e=off+16;if(link===1&&n>=34){const eth=(u[e+12]<<8)|u[e+13];if(eth===0x0800){const proto=u[e+14+9];if(proto===6)tcp++;else if(proto===17)udp++;else if(proto===1)icmp++}}off+=16+n}return {magic,linkType:link,packets,bytes,tcp,udp,icmp}};