export type Guide={slug:string;title:string;description:string;intro:string;sections:Array<{heading:string;body:string}>;toolSlugs:string[]};

export const guides:Guide[]=[
 {slug:"compress-image-to-100kb",title:"How to Compress an Image to 100KB",description:"A practical guide to reducing image file size to around 100KB while keeping text and photos readable.",intro:"Many application forms and upload portals set a small image-size limit. The reliable approach is to start with the original image, choose a target near 100KB, and then check the visual result rather than assuming the smallest file is automatically the best one.",sections:[
  {heading:"1. Start with the original image",body:"Work from the highest-quality copy you have. Repeatedly compressing an already-compressed JPEG can introduce visible artifacts and gives you less room to reach a good result."},
  {heading:"2. Choose the 100KB target",body:"Open the image compressor and use the 100KB preset or enter a custom target. Photographs usually respond well to JPEG or WebP compression; screenshots containing small text may need more careful settings."},
  {heading:"3. Check readability after compression",body:"Open the generated file at its intended display size. Look for blurry text, blocky edges, halos around letters and loss of fine detail. A file that is under the limit but unreadable is not a successful conversion."},
  {heading:"4. Reduce dimensions when quality alone is not enough",body:"Very large images contain more pixels than many upload forms need. Reducing dimensions can lower file size substantially while preserving better apparent quality than aggressively lowering quality on an oversized image."}
 ],toolSlugs:["compress-image","resize-image"]},
 {slug:"reduce-jpg-below-500kb",title:"How to Reduce a JPG Below 500KB",description:"Learn a practical way to reduce a JPG file below 500KB for websites, forms and email.",intro:"A 500KB ceiling is common for profile photos, document portals and web uploads. The goal is not just to hit a number; it is to keep the important visual information intact while reducing unnecessary bytes.",sections:[
  {heading:"Use a target-size workflow",body:"Upload the JPG, choose a target around 500KB and generate a result. If the source is much larger, consider reducing its dimensions before pushing quality settings too low."},
  {heading:"Photographs and screenshots behave differently",body:"A photograph often compresses well because nearby pixels are similar. A screenshot with text, sharp UI edges or flat colors may need a higher-quality setting or a different format to avoid visible artifacts."},
  {heading:"Verify the final file",body:"Check both the file size and the image dimensions. Some websites validate the actual byte size, while others also impose width, height or format requirements."}
 ],toolSlugs:["compress-image","resize-image"]},
 {slug:"convert-pdf-to-word-without-losing-text",title:"How to Convert PDF to Word Without Losing Text",description:"Understand when PDF-to-Word conversion works well, why formatting changes, and what to check in the DOCX result.",intro:"PDF and DOCX are built for different jobs: PDF preserves fixed layout while DOCX is designed for editing and reflow. A good PDF-to-Word workflow therefore focuses first on extracting the text correctly and then on checking the converted layout.",sections:[
  {heading:"Check whether the PDF has selectable text",body:"Try selecting a sentence in the PDF viewer. If characters can be selected and copied, text extraction is usually much more straightforward. If each page behaves like a picture, OCR may be needed instead."},
  {heading:"Expect layout differences",body:"Columns, tables, floating objects, unusual fonts and precise positioning can change during conversion because the destination format uses a different layout model. Review the DOCX before using it as the final document."},
  {heading:"Review names, numbers and tables",body:"Conversion errors are especially costly in dates, amounts, names, URLs and table cells. Compare important sections with the original PDF instead of relying on visual similarity alone."}
 ],toolSlugs:["pdf-to-word","pdf-to-docs"]},
 {slug:"make-a-clean-scanned-pdf",title:"How to Make a Clean Scanned PDF",description:"Turn photographed or existing PDF pages into a cleaner scanned-style document and understand the trade-offs.",intro:"A scanned-style PDF can be useful when the visual appearance of a physical scan is required. The workflow is different from OCR: scan-style processing changes page appearance, while OCR creates searchable or editable text.",sections:[
  {heading:"Start with a clear page",body:"For a phone photo, place the page on a flat surface, use even lighting and keep the full page inside the frame. Better input produces a better scan-style result."},
  {heading:"Choose grayscale or black and white",body:"Grayscale keeps more detail and can be better for stamps, signatures and faint marks. Black and white is useful for clean text documents where a simpler appearance is preferred."},
  {heading:"Know the image-only trade-off",body:"Rasterizing a PDF creates image pages. That can remove the original selectable-text layer, so keep the original source if you may need search, copy/paste or editing later."}
 ],toolSlugs:["scan-image","scan-pdf","images-to-pdf"]},
 {slug:"how-ats-resume-scanners-work",title:"How ATS Resume Scanners Work",description:"A practical explanation of resume parsing, sections, keywords and why formatting can affect automated screening.",intro:"An applicant tracking system (ATS) is used by employers to organize and process applications. Exact vendor rules vary, so a useful resume audit should focus on robust fundamentals rather than chasing a single mythical score.",sections:[
  {heading:"Readable structure comes first",body:"Use clear section headings, consistent dates and straightforward text. A resume that a person can easily scan is also less likely to confuse a parser."},
  {heading:"Keywords should reflect the job",body:"Compare the job description with your real skills, tools and experience. Use relevant terminology naturally in context, supported by evidence, instead of creating a keyword list with no substance."},
  {heading:"Impact is more useful than duties",body:"Where possible, describe what changed because of your work: reduced time, improved reliability, built a feature, investigated an incident, or completed a measurable result. Concrete evidence gives both humans and automated reviews more signal."}
 ],toolSlugs:["ats-resume-score"]},
 {slug:"improve-ats-resume-score",title:"How to Improve an ATS Resume Score",description:"A practical checklist for improving resume readability, section structure, impact and job-description alignment.",intro:"An ATS score should be treated as feedback, not a hiring guarantee. Improve the fundamentals first: make the document easy to parse, easy to scan and genuinely relevant to the specific role.",sections:[
  {heading:"Use standard sections",body:"Keep core information in recognizable sections such as Summary, Experience, Education, Skills and Projects where they apply. Avoid hiding important details inside decorative graphics."},
  {heading:"Match the role honestly",body:"Read the job description and identify recurring skills, technologies, responsibilities and domain terms that genuinely match your background. Add the relevant wording where it accurately describes your experience."},
  {heading:"Strengthen bullets with evidence",body:"Replace vague claims with action plus outcome. For technical work, mention the system, tool or method used and what it accomplished when that information is truthful and useful."},
  {heading:"Run a human review",body:"After automated checks, read the complete resume as a recruiter would. Remove repetition, correct dates and verify every technical claim."}
 ],toolSlugs:["ats-resume-score"]},
 {slug:"jpg-vs-pdf-which-should-you-use",title:"JPG vs PDF: Which Should You Use?",description:"Choose between JPG and PDF for photos, scans, applications, reports and multi-page documents.",intro:"JPG and PDF solve different problems. JPG is an image format; PDF is a document container designed to preserve page layout. The right choice depends on whether you are sharing a single image or a complete document.",sections:[
  {heading:"Choose JPG for a single image",body:"JPG is a practical format for photographs and other continuous-tone images. It is widely supported and can be compressed to small sizes."},
  {heading:"Choose PDF for documents and multiple pages",body:"PDF is usually the better fit for applications, reports and multi-page scans because pages stay together and the document can preserve text, images and layout in one file."},
  {heading:"Check the portal requirement",body:"Upload systems often specify accepted formats and size limits. Follow those requirements first, then optimize the file only as much as needed."}
 ],toolSlugs:["images-to-pdf","compress-image","pdf-to-word"]},
 {slug:"how-to-edit-a-pdf-online",title:"How to Edit a PDF Online for Simple Changes",description:"Learn when a browser-based PDF editor is enough for adding text, rotating pages and removing pages.",intro:"Not every PDF edit needs a full desktop editor. For quick structural changes, a focused browser tool can be faster, but complex layout work still needs dedicated PDF software.",sections:[
  {heading:"Good tasks for a lightweight editor",body:"Adding a short note, correcting a page orientation or deleting an unwanted page are straightforward examples of edits that do not require rebuilding the entire document."},
  {heading:"Review page order and placement",body:"After editing, check every page in the generated file. Confirm that inserted text is positioned correctly, rotations are correct and deleted pages are actually gone."},
  {heading:"Keep the original for important documents",body:"Save the original source before editing. That gives you a clean fallback if the result needs further changes or if a complex document does not reproduce perfectly."}
 ],toolSlugs:["edit-pdf"]}
];

export function getGuide(slug:string){return guides.find(g=>g.slug===slug);}
