"use client";import{useState}from"react";import type{Tool}from"@/lib/tools";import{api,digest,fileDigest,identifyHash,b64e,b64d,hexe,hexd,urlInfo,passwordScore,regexInfo,csp,cidr,meta,logAnalyze,yaraLite,pcap,entropy,chmod,portRange,unixTime,jsonToTs,jsonToCsv,iocs,stix}from"@/lib/cyber-tools";
const Field=({label,value,set,type="text",placeholder=""}:{label:string;value:string;set:(v:string)=>void;type?:string;placeholder?:string})=><div className="field"><label>{label}</label><input type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></div>;
export default function CyberToolRunner({tool}:{tool:Tool}){const[a,setA]=useState(""),[b,setB]=useState(""),[r,setR]=useState(""),[err,setErr]=useState(""),[status,setStatus]=useState(""),[file,setFile]=useState<File|null>(null),[alg,setAlg]=useState("SHA-256"),[mode,setMode]=useState("base64-encode"),[flags,setFlags]=useState(""),[dns,setDns]=useState("A"),[cspOpt,setCspOpt]=useState({scripts:true,styles:true,images:true,fonts:true,frames:false,connect:true});
const out=(x:unknown)=>setR(typeof x==="string"?x:JSON.stringify(x,null,2));const run=async()=>{setStatus("Working…");setErr("");setR("");try{switch(tool.slug){
case"http-security-header-analyzer":out(await api("/api/security/headers",{url:a}));break;
case"jwt-analyzer":{const p=a.trim().split(".");if(p.length!==3)throw Error("Enter a JWT with three parts.");const dec=(x:string)=>JSON.parse(b64d(x.replace(/-/g,"+").replace(/_/g,"/")));const h=dec(p[0]),q=dec(p[1]);out({header:h,payload:q,algorithm:h.alg,type:h.typ,expires:q.exp?new Date(q.exp*1000).toISOString():"not set",expired:q.exp?Date.now()/1000>q.exp:false});break}
case"hash-generator":out(await api("/api/security/hash",{value:a,algorithm:alg}));break;case"hash-identifier":out(identifyHash(a));break;
case"base64-url-hex":out((mode==="base64-encode"?b64e:mode==="base64-decode"?b64d:mode==="url-encode"?encodeURIComponent:mode==="url-decode"?decodeURIComponent:mode==="hex-encode"?hexe:hexd)(a));break;
case"url-domain-analyzer":out(urlInfo(a));break;case"password-strength-analyzer":out(passwordScore(a));break;case"regex-security-tester":out(regexInfo(a,flags));break;case"csp-generator":out(csp(cspOpt));break;
case"security-txt-generator":out(["Contact: "+a,"Policy: "+b].join("\n")+"\n");break;case"ip-cidr-calculator":out(cidr(a));break;
case"dns-record-analyzer":out(await api("/api/security/dns?domain="+encodeURIComponent(a)+"&type="+dns));break;case"tls-ssl-analyzer":out(await api("/api/security/tls",{host:a,port:Number(b)||443}));break;case"whois-rdap-lookup":out(await api("/api/security/rdap?domain="+encodeURIComponent(a)));break;
case"file-hash-calculator":if(!file)throw Error("Choose a file.");out({file:file.name,size:file.size,hash:await fileDigest(file,alg)});break;case"file-forensics":if(!file)throw Error("Choose a file.");{const buf=new Uint8Array(await file.arrayBuffer()),sample=buf.slice(0,4096),counts=new Uint32Array(256);for(const x of sample)counts[x]++;let h=0;for(const n of counts){if(n){const p=n/sample.length;h-=p*Math.log2(p)}}out({name:file.name,type:file.type,size:file.size,firstBytes:[...buf.slice(0,16)].map(x=>x.toString(16).padStart(2,"0")).join(" "),sampleEntropy:Number(h.toFixed(4)),sha256:await fileDigest(file,"SHA-256")});}break;case"exif-metadata-viewer":if(!file)throw Error("Choose an image.");out(await meta(file));break;
case"qr-security-analyzer":{let v=a;if(!v&&file&&"BarcodeDetector" in window){const BD=(window as any).BarcodeDetector,bd=new BD({formats:["qr_code"]}),found=await bd.detect(file);if(found.length)v=found[0].rawValue}if(!v)throw Error("Paste the decoded QR URL or use a browser with QR BarcodeDetector support.");const u=new URL(v),flags:string[]=[];if(u.protocol!=="https:")flags.push("Destination does not use HTTPS.");if(/^\\d+(?:\\.\\d+){3}$/.test(u.hostname))flags.push("URL uses a raw IPv4 address.");if(/^(bit\\.ly|tinyurl\\.com|t\\.co|goo\\.gl)$/i.test(u.hostname))flags.push("URL uses a common shortener.");out({url:v,hostname:u.hostname,flags,risk:flags.length>=2?"HIGH":flags.length===1?"MEDIUM":"LOW"});break;}
case"ioc-analyzer":{const v=a.trim();out({indicator:v,type:/^(?:\d{1,3}\.){3}\d{1,3}$/.test(v)?"IPv4":/^[a-f0-9]{32}$/i.test(v)?"MD5":/^[a-f0-9]{40}$/i.test(v)?"SHA-1":/^[a-f0-9]{64}$/i.test(v)?"SHA-256":v.includes(".")?"Domain":"Unknown",normalized:v.toLowerCase()});break}
case"yara-rule-tester":if(!file)throw Error("Choose a file.");out(yaraLite(a,await file.text()));break;case"log-analyzer":if(!file)throw Error("Choose a log file.");out(logAnalyze(await file.text()));break;case"pcap-analyzer":if(!file)throw Error("Choose a PCAP.");out(await pcap(file));break;case"entropy-calculator":out(entropy(a));break;case"chmod-calculator":out(chmod(a));break;case"port-range-calculator":out(portRange(a));break;case"unix-timestamp-converter":out(unixTime(a));break;case"json-to-typescript":out(jsonToTs(a));break;case"json-to-csv":out(jsonToCsv(a));break;case"ioc-extractor":out(iocs(a));break;case"stix-ioc-exporter":out(stix(a));break;case"security-report-generator":{const u=a.trim();if(!u)throw Error("Enter a domain or URL.");const url=/^https?:\/\//i.test(u)?u:"https://"+u;const host=new URL(url).hostname;const [headers,dns,tls,rdap]=await Promise.allSettled([api("/api/security/headers",{url}),api("/api/security/dns?domain="+encodeURIComponent(host)+"&type=A"),api("/api/security/tls",{host,port:443}),api("/api/security/rdap?domain="+encodeURIComponent(host))]);out({domain:host,httpHeaders:headers.status==="fulfilled"?headers.value:headers.reason?.message,dns:dns.status==="fulfilled"?dns.value:dns.reason?.message,tls:tls.status==="fulfilled"?tls.value:tls.reason?.message,rdap:rdap.status==="fulfilled"?rdap.value:rdap.reason?.message});break;}case"cvss-calculator":{const v=Number(a);if(!Number.isFinite(v)||v<0||v>10)throw Error("Enter a CVSS score from 0 to 10.");out({baseScore:v,band:v===0?"None":v<=3.9?"Low":v<=6.9?"Medium":v<=8.9?"High":"Critical"});break;}case"cron-expression-helper":{const p=a.trim().split(/\s+/);if(p.length!==5)throw Error("Use five cron fields: minute hour day month weekday.");out({valid:true,fields:{minute:p[0],hour:p[1],day:p[2],month:p[3],weekday:p[4]}});break;}case"universal-security-analyzer":{const v=a.trim(),p=v.split(".");if(p.length===3&&p.every(x=>x.length))out({type:"JWT",hint:"Use JWT Analyzer for detailed claims."});else if(/^(?:\d{1,3}\.){3}\d{1,3}$/.test(v))out({type:"IPv4",value:v});else if(/^[a-f0-9]{32}$|^[a-f0-9]{40}$|^[a-f0-9]{64}$/i.test(v))out({type:"Hash",identification:identifyHash(v)});else if(/^https?:\/\//i.test(v))out({type:"URL",details:urlInfo(v)});else out({type:"Domain or text",value:v});break;}default:throw Error("Unsupported security tool.")}setStatus("Done")}catch(e){setStatus("");setErr(e instanceof Error?e.message:"Something went wrong.")}};
const fileTool=["file-forensics","file-hash-calculator","exif-metadata-viewer","qr-security-analyzer","yara-rule-tester","log-analyzer","pcap-analyzer"].includes(tool.slug);
return <div className="card runner"><div className="runnerhead"><div><h2>Use {tool.name}</h2><div className="sub">Browser-first security utility. Do not submit passwords, private keys or production secrets.</div></div><span className="pill">SECURITY</span></div>
{tool.slug==="http-security-header-analyzer"&&<div className="form">{Field({label:"Website URL",value:a,set:setA,type:"url",placeholder:"https://example.com"})}</div>}
{tool.slug==="jwt-analyzer"&&<div className="form"><div className="field full"><label>JWT</label><textarea value={a} onChange={e=>setA(e.target.value)}/></div></div>}
{["hash-generator","hash-identifier"].includes(tool.slug)&&<div className="form"><div className="field full"><label>Input</label><textarea value={a} onChange={e=>setA(e.target.value)}/></div>{tool.slug==="hash-generator"&&<div className="field"><label>Algorithm</label><select value={alg} onChange={e=>setAlg(e.target.value)}>{["MD5","SHA-1","SHA-256","SHA-384","SHA-512"].map(x=><option key={x}>{x}</option>)}</select></div>}</div>}
{tool.slug==="base64-url-hex"&&<div className="form"><div className="field"><label>Operation</label><select value={mode} onChange={e=>setMode(e.target.value)}><option value="base64-encode">Base64 encode</option><option value="base64-decode">Base64 decode</option><option value="url-encode">URL encode</option><option value="url-decode">URL decode</option><option value="hex-encode">Hex encode</option><option value="hex-decode">Hex decode</option></select></div><div className="field full"><label>Input</label><textarea value={a} onChange={e=>setA(e.target.value)}/></div></div>}
{tool.slug==="url-domain-analyzer"&&<div className="form">{Field({label:"URL",value:a,set:setA,type:"url",placeholder:"https://example.com:8443/path?q=1"})}</div>}
{tool.slug==="password-strength-analyzer"&&<div className="form">{Field({label:"Password",value:a,set:setA,type:"password"})}</div>}
{tool.slug==="regex-security-tester"&&<div className="form">{Field({label:"Regex",value:a,set:setA,placeholder:"^(a+)+$"})}{Field({label:"Flags",value:flags,set:setFlags,placeholder:"gi"})}</div>}
{tool.slug==="csp-generator"&&<div className="form">{Object.keys(cspOpt).map(k=><div className="field" key={k}><label>{k}</label><select value={cspOpt[k as keyof typeof cspOpt]?"yes":"no"} onChange={e=>setCspOpt({...cspOpt,[k]:e.target.value==="yes"})}><option value="yes">Allow</option><option value="no">Deny</option></select></div>)}</div>}
{tool.slug==="security-txt-generator"&&<div className="form">{Field({label:"Contact",value:a,set:setA,placeholder:"mailto:security@example.com"})}{Field({label:"Policy URL",value:b,set:setB,type:"url",placeholder:"https://example.com/security"})}</div>}
{tool.slug==="ip-cidr-calculator"&&<div className="form">{Field({label:"IPv4 CIDR",value:a,set:setA,placeholder:"192.168.1.0/24"})}</div>}
{tool.slug==="dns-record-analyzer"&&<div className="form">{Field({label:"Domain",value:a,set:setA,placeholder:"example.com"})}<div className="field"><label>Record</label><select value={dns} onChange={e=>setDns(e.target.value)}>{["A","AAAA","CNAME","MX","TXT","NS"].map(x=><option key={x}>{x}</option>)}</select></div></div>}
{tool.slug==="tls-ssl-analyzer"&&<div className="form">{Field({label:"Hostname",value:a,set:setA,placeholder:"example.com"})}{Field({label:"Port",value:b,set:setB,placeholder:"443"})}</div>}
{tool.slug==="whois-rdap-lookup"&&<div className="form">{Field({label:"Domain",value:a,set:setA,placeholder:"example.com"})}</div>}
{tool.slug==="qr-security-analyzer"&&<div className="form">{Field({label:"Decoded QR URL",value:a,set:setA,type:"url",placeholder:"https://example.com"})}</div>}
{fileTool&&<div className="upload"><input id="cyber-file" type="file" accept={tool.slug==="pcap-analyzer"?".pcap,.cap":tool.slug==="log-analyzer"?".log,.txt":"*/*"} onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="meta">{file?.name||"No file selected"}</div></div>}
{["entropy-calculator","chmod-calculator","port-range-calculator","unix-timestamp-converter","json-to-typescript","json-to-csv","ioc-extractor","stix-ioc-exporter","universal-security-analyzer"].includes(tool.slug)&&<div className="form"><div className="field full"><label>Input</label><textarea value={a} onChange={e=>setA(e.target.value)} placeholder={tool.slug==="chmod-calculator"?"755 or rwxr-xr-x":tool.slug==="port-range-calculator"?"1-1024":tool.slug==="unix-timestamp-converter"?"1728000000":"Paste text or JSON here"}/></div></div>}{tool.slug==="yara-rule-tester"&&<div className="form"><div className="field full"><label>YARA rule</label><textarea value={a} onChange={e=>setA(e.target.value)} placeholder={'rule Demo { strings: $a = "test" condition: $a }'}/></div></div>}
<div className="runactions"><button className="btn primary" onClick={()=>void run()}>{status||"Run tool"}</button>{r&&<button className="btn" onClick={()=>setR("")}>Clear</button>}</div>{err&&<div className="error">{err}</div>}{r&&<div className="result"><div className="resultlabel">Result</div><pre className="resultvalue">{r}</pre></div>}</div>}